-- 2024 08 16
SELECT B.AUTHOR_ID AS AUTHOR_ID , A.AUTHOR_NAME AS AUTHOR_NAME , B.CATEGORY AS CATEGORY, SUM(S.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE LEFT(SALES_DATE,7) = '2022-01'
GROUP BY  B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID ASC , CATEGORY DESC;