-- 2024 08 09
-- 테이블에서 레벨 나눌 때 좋은 예시


SELECT E1.ID
FROM ECOLI_DATA E1
INNER JOIN ECOLI_DATA E2 ON E1.PARENT_ID = E2.ID
INNER JOIN ECOLI_DATA E3 ON E2.PARENT_ID = E3.ID
WHERE E1.PARENT_ID IS NOT NULL 
  AND E2.PARENT_ID IS NOT NULL 
  AND E3.PARENT_ID IS NULL;


