-- 2024 08 15

SELECT I.ITEM_ID AS ITEM_ID , I.ITEM_NAME AS ITEM_NAME, I.RARITY AS RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;