-- 2024 08 08



SELECT ID, IFNULL(CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS A
LEFT JOIN(  
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) AS B
ON A.ID = B.PARENT_ID
ORDER BY ID;