-- 2024 08 09 1트

SELECT 
    ID,
    CASE
        WHEN PERCENT_RANK_VAL >= 0 AND PERCENT_RANK_VAL <= 0.25 THEN 'CRITICAL'
        WHEN PERCENT_RANK_VAL > 0.25 AND PERCENT_RANK_VAL <= 0.50 THEN 'HIGH'
        WHEN PERCENT_RANK_VAL > 0.50 AND PERCENT_RANK_VAL <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        GENOTYPE,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT_RANK_VAL
    FROM
        ECOLI_DATA
) AS SIZE
ORDER BY ID;
