-- 2024 08 09

SELECT EC1.ID AS ID, EC1.GENOTYPE AS GENOTYPE, EC2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS EC1
INNER JOIN ECOLI_DATA AS EC2
ON EC1.PARENT_ID = EC2.ID
WHERE EC1.GENOTYPE & EC2.GENOTYPE = EC2.GENOTYPE
ORDER BY ID;