-- 코드를 입력하세요
SELECT B.TITLE,	B.BOARD_ID,	R.REPLY_ID,	R.WRITER_ID,	R.CONTENTS,	 DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_BOARD B, USED_GOODS_REPLY R
where B.BOARD_ID = R.BOARD_ID AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC
