-- 2024 08 15
SELECT B.CATEGORY AS CATEGORY , SUM(SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE LEFT(SALES_DATE,7) = '2022-01'
GROUP BY B.CATEGORY
ORDER BY CATEGORY ASC;